### PR TITLE
remove mention of 'uninomial' from notes

### PR DESCRIPTION
**Pull request by nielsklazenga**
- for dwc:specificEpithet and dwc:infraspecificEpithet

### CODE REVIEW

**Comment by nielsklazenga** [comment]
All parsed name properties come from Darwin Core, which does not have the 'uninomial' property. The usage notes come from the TDWG Taxon Name LSID Ontology which does. We can add a uninomial property if requested by the community, but it would be better in Darwin Core and it has never been requested there, so there is probably no use for it.

**Comment by ghwhitbread** [comment]
Puzzled by this one @nielsklazenga.  Uninomial is a TCS property.  It is also used in NSL exports, ABCD and CoLDP etc.

**Comment by nielsklazenga** [comment]
Then we need to add it in TCS 2. I think though that, since we borrow all the parsed name properties from Darwin Core, the better approach, if people want to have it, would be to add it to Darwin Core. We can do that as the TCS MG (well, we can propose it (or we can add the TAG what to do about it)).

This pull request is only about the text of the comments under `specificEpithet` and `infraspecificEpithet`, not about whether or not we should have the `uninomial` property. At the moment the reference to a `uninomial` property is just wrong.

Alternatively, I can just add the `uninomial` property and we work out later how exactly we deal with that. I can add that to this PR.

**Comment by ghwhitbread** [comment]
But already there as https://github.com/tdwg/tcs2/issues/18, because "uninomial" is in TCS101.

**Comment by nielsklazenga** [comment]
That is just the issue. It has a note from Feb. 19 that it is better off in Darwin Core. But I will add it to the YAML. Will need to create a new PR for that, as the branch is not there anymore.

**Comment by ghwhitbread** [comment]
I think I see your point.

**Pull request merged**
